import "dotenv/config";

const env = (key: string, fallback?: string): string => {
  const v = process.env[key];
  if (v === undefined || v === "") return fallback ?? "";
  return v;
};

const corsOrigins = env("CORS_ORIGINS", "http://localhost:3000,http://localhost:3001")
  .split(",")
  .map(s => s.trim())
  .filter(Boolean);

export const config = {
  port: Number(env("PORT", "8090")),
  host: env("HOST", "0.0.0.0"),
  corsOrigins,
  // Address whose balance / nonce the dapp should see. Defaults to vitalik.eth.
  impersonatedAddress: env(
    "IMPERSONATED_ADDRESS",
    "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
  ),
  chainId: Number(env("CHAIN_ID", "1")),
  // Upstream RPC — we keep the API key server-side and proxy from /__slop_rpc.
  // Falls back to a public Cloudflare gateway only if Alchemy isn't configured;
  // production runs should always set ALCHEMY_API_KEY.
  alchemyApiKey: env("ALCHEMY_API_KEY", ""),
  rpcUrl: env("RPC_URL", ""),
  viewport: {
    width: Number(env("VIEWPORT_WIDTH", "1280")),
    height: Number(env("VIEWPORT_HEIGHT", "800")),
  },
  screencast: {
    quality: Number(env("SCREENCAST_QUALITY", "60")),
    everyNthFrame: Number(env("SCREENCAST_EVERY_NTH_FRAME", "1")),
    maxWidth: Number(env("SCREENCAST_MAX_WIDTH", "1280")),
    maxHeight: Number(env("SCREENCAST_MAX_HEIGHT", "800")),
  },
  // Where to forward captured calldata. The browser-host POSTs to this URL
  // so the relay can broadcast over its tx_request channel. Optional —
  // unset means "don't forward, just log".
  relayTxBroadcastUrl: env("RELAY_TX_BROADCAST_URL", ""),
  relayTxBroadcastSecret: env("RELAY_TX_BROADCAST_SECRET", ""),
  // Pinned UA the host advertises on every page. Defaults to a current
  // Linux x86_64 Chrome string so navigator.platform matches the prod
  // box's actual OS (Mac UA + Linux platform is itself a fingerprint).
  // Bump the Chrome major version every few months to stay current.
  userAgent: env(
    "BROWSER_USER_AGENT",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
  ),
  // Path to a JSON file containing cookies to inject into every new
  // BrowserContext. Generated by `yarn warmup` (a separate headful
  // session where the operator browses Google etc. to pick up real
  // bot-detection cookies). Missing/unreadable file is a no-op.
  cookiesPath: env("COOKIES_PATH", "cookies.json"),
};

// Chains the impersonator knows how to proxy. The frontend picks from
// this set in its network selector, and `wallet_switchEthereumChain`
// calls validate against it. To add a chain: append { chainId,
// alchemySubdomain, label } and the rest works automatically. An entry
// with `rpcUrl` set bypasses Alchemy entirely and proxies that URL —
// for chains Alchemy supports but our app doesn't have enabled.
export const SUPPORTED_CHAINS: Record<number, { alchemySubdomain: string; label: string; rpcUrl?: string }> = {
  1: { alchemySubdomain: "eth-mainnet", label: "Ethereum" },
  8453: { alchemySubdomain: "base-mainnet", label: "Base" },
  100: { alchemySubdomain: "gnosis-mainnet", label: "Gnosis" },
  42161: { alchemySubdomain: "arb-mainnet", label: "Arbitrum" },
  10: { alchemySubdomain: "opt-mainnet", label: "Optimism" },
  137: { alchemySubdomain: "polygon-mainnet", label: "Polygon" },
  11155111: { alchemySubdomain: "eth-sepolia", label: "Sepolia" },
  // Drop rpcUrl once ROBINHOOD_MAINNET is enabled on our Alchemy app.
  4663: {
    alchemySubdomain: "robinhood-mainnet",
    label: "Robinhood",
    rpcUrl: "https://rpc.mainnet.chain.robinhood.com",
  },
};

export const isSupportedChain = (chainId: number): boolean => chainId in SUPPORTED_CHAINS;

export const upstreamRpcUrl = (chainId: number): string => {
  if (config.rpcUrl && chainId === config.chainId) return config.rpcUrl;
  const perChainRpc = SUPPORTED_CHAINS[chainId]?.rpcUrl;
  if (perChainRpc) return perChainRpc;
  if (config.alchemyApiKey) {
    const sub = SUPPORTED_CHAINS[chainId]?.alchemySubdomain ?? "eth-mainnet";
    return `https://${sub}.g.alchemy.com/v2/${config.alchemyApiKey}`;
  }
  // Last-resort public fallback. Per the user's RPC rule we should never
  // ship without an Alchemy key, but local dev with no key gets a working
  // (slow, rate-limited) endpoint instead of a hard crash.
  return "https://cloudflare-eth.com";
};
