/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const externalContracts = {
  1: {
    SlopComputer: {
      address: "0xf3ce3614fe8cd4294a0bf05d10cfda9d9cbc4886",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "ENS_REVERSE_REGISTRAR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "addEpisode",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "liveSlug",
              type: "string",
              internalType: "string",
            },
            {
              name: "manifest",
              type: "string",
              internalType: "string",
            },
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
            {
              name: "datetime",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deleteEpisode",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "episodeCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "execute",
          inputs: [
            {
              name: "target",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getEpisode",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEpisodeBySlug",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEpisodes",
          inputs: [
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "episodes",
              type: "tuple[]",
              internalType: "struct SlopComputer.Episode[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEpisodesFrom",
          inputs: [
            {
              name: "startId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "episodes",
              type: "tuple[]",
              internalType: "struct SlopComputer.Episode[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getId",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "datetime",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "goLive",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "liveSlug",
              type: "string",
              internalType: "string",
            },
            {
              name: "manifest",
              type: "string",
              internalType: "string",
            },
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
            {
              name: "datetime",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "goOffline",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "head",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "indexOf",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "latest",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "live",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "liveEpisode",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setEpisodeContract",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setLive",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setLiveSlug",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "newLiveSlug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setManifest",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "manifest",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setName",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSlug",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "newSlug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "slugToId",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "EpisodeAdded",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "liveSlug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "manifest",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "contractAddr",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "datetime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeContractSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "contractAddr",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeDeleted",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeLiveSlugSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "liveSlug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeManifestSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "manifest",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeSlugSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Executed",
          inputs: [
            {
              name: "target",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NameSet",
          inputs: [
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "node",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WentLive",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "previousLive",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "resumed",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WentOffline",
          inputs: [
            {
              name: "previousLive",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EpisodeAlreadyExists",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "EpisodeIsLive",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "EpisodeNotFound",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "NotLive",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SlugAlreadyTaken",
          inputs: [],
        },
        {
          type: "error",
          name: "SlugInvalid",
          inputs: [],
        },
        {
          type: "error",
          name: "SlugNotFound",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 25189471,
    },
  },
  31337: {
    SlopComputer: {
      address: "0xd49880bddfac4fd20d3b6bee01c71231c0c63789",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "ENS_REVERSE_REGISTRAR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "addEpisode",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "liveSlug",
              type: "string",
              internalType: "string",
            },
            {
              name: "manifest",
              type: "string",
              internalType: "string",
            },
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
            {
              name: "datetime",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deleteEpisode",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "episodeCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "execute",
          inputs: [
            {
              name: "target",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getEpisode",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEpisodeBySlug",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEpisodes",
          inputs: [
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "episodes",
              type: "tuple[]",
              internalType: "struct SlopComputer.Episode[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEpisodesFrom",
          inputs: [
            {
              name: "startId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "episodes",
              type: "tuple[]",
              internalType: "struct SlopComputer.Episode[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getId",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "datetime",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "goLive",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "liveSlug",
              type: "string",
              internalType: "string",
            },
            {
              name: "manifest",
              type: "string",
              internalType: "string",
            },
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
            {
              name: "datetime",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "goOffline",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "head",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "indexOf",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "latest",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "live",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "liveEpisode",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct SlopComputer.Episode",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "liveSlug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "manifest",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contractAddr",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "datetime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "addedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setEpisodeContract",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setLive",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setLiveSlug",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "newLiveSlug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setManifest",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "manifest",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setName",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSlug",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "newSlug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "slugToId",
          inputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "EpisodeAdded",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "liveSlug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "manifest",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "contractAddr",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "datetime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeContractSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "contractAddr",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeDeleted",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeLiveSlugSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "liveSlug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeManifestSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "manifest",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "EpisodeSlugSet",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Executed",
          inputs: [
            {
              name: "target",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NameSet",
          inputs: [
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "node",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WentLive",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "previousLive",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "resumed",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WentOffline",
          inputs: [
            {
              name: "previousLive",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EpisodeAlreadyExists",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "EpisodeIsLive",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "EpisodeNotFound",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "NotLive",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SlugAlreadyTaken",
          inputs: [],
        },
        {
          type: "error",
          name: "SlugInvalid",
          inputs: [],
        },
        {
          type: "error",
          name: "SlugNotFound",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 46,
    },
  },
} as const;

export default externalContracts satisfies GenericContractsDeclaration;
